name: Automerge Pull Requests
on:
  pull_request:
    branches: [master, next, develop, alpha, beta]
    types: [labeled, closed]
jobs:
  automerge:
    name: Automerge Pull Request
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ format('{0}{1}', github.event.pull_request.number, github.event.issue.number) }}
    # IF event type is non fork PR or comment on PR from desivi with '/release'
    if: >-
      (
        github.event_name == 'pull_request'
        && github.event.pull_request.head.repo.full_name == github.repository
        && contains(github.event.pull_request.labels.*.name, 'formatted')
        && contains(github.event.pull_request.labels.*.name, 'linted')
        && contains(github.event.pull_request.labels.*.name, 'conventional')
        && contains(github.event.pull_request.labels.*.name, 'builds')
        && contains(github.event.pull_request.labels.*.name, 'tested')
        && contains(github.event.pull_request.labels.*.name, 'covered')
        && ! contains(github.event.pull_request.labels.*.name, 'automated merge')
        && ! contains(github.event.pull_request.labels.*.name, 'hold merge')
      ) || (
        github.event_name == 'issue_comment'
        && github.event.issue.pull_request != ''
        && contains(github.event.comment.body, '/release')
        && github.actor == 'desivi'
        && contains(github.event.pull_request.labels.*.name, 'formatted')
        && contains(github.event.pull_request.labels.*.name, 'linted')
        && contains(github.event.pull_request.labels.*.name, 'conventional')
        && contains(github.event.pull_request.labels.*.name, 'builds')
        && contains(github.event.pull_request.labels.*.name, 'tested')
        && contains(github.event.pull_request.labels.*.name, 'covered')
        && ! contains(github.event.issue.labels.*.name, 'automated merge')
        && ! contains(github.event.issue.labels.*.name, 'hold merge'))
    steps:
      # IF formatted, builds, and tested labels then merge
      - name: if formatted, builds, tested merge automerge pr
        uses: pascalgn/automerge-action@v0.7.5
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          MERGE_METHOD: merge
          # This breaks the /release on issue_comment portion unless I get the head.ref from github-script
          MERGE_COMMIT_MESSAGE: 'Auto merge from ${{ github.event.pull_request.head.ref }} PR#{pullRequest.number}: {pullRequest.title}'
          UPDATE_METHOD: merge
          MERGE_LABELS: 'formatted,builds,tested,linted,covered,conventional'
          UPDATE_LABELS: ''
        # IF failure, get payload of PR and notify
      - name: if failure, get pr payload
        uses: actions/github-script@0.8.0
        id: pr_json
        if: failure()
        with:
          github-token: ${{env.GITHUB_TOKEN}}
          script: |
            const result = await github.pulls.get({
              owner: '${{ github.repository }}'.split('/')[0],
              repo: '${{ github.repository }}'.split('/')[1],
              pull_number: ${{ env.PR_NUMBER }}
            })
            return result.data;
      - name: if failure, set pr payload outputs
        if: failure()
        id: pr
        run: |
          echo '${{ steps.pr_json.outputs.result }}' > pr.json
          echo "::set-output name=user::$( jq -r '.user.login' pr.json )"
          echo "::set-output name=head::$( jq -r '.head.repo.full_name' pr.json )"
          echo "::set-output name=head_url::$( jq -r '.head.repo.html_url' pr.json )"
          echo "::set-output name=base::$( jq -r '.base.repo.full_name' pr.json )"
          echo "::set-output name=base_url::$( jq -r '.base.repo.html_url' pr.json )"
      - name: IF failure, notify
        uses: peter-evans/create-or-update-comment@v1
        if: failure()
        with:
          token: ${{ env.GITHUB_TOKEN }}
          issue-number: ${{ env.PR_NUMBER }}
          body: |
            @${{ steps.pr.outputs.user }}, ${{ env.AUTHOR }} - it appears that there was an issue with the merge.

            Head Repo/Branch: **[${{ steps.pr.outputs.head }}]**(${{ steps.pr.outputs.head_url }}) merge into **[${{ steps.pr.outputs.base }}]**(${{ steps.pr.outputs.base_url }})

            ## Event JSON
            ```json
              ${{ toJSON(steps.pr_json.outputs.result)}}
            ```
      - name: IF failure, assign failure label
        uses: actions/github-script@0.6.0
        if: failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if ('${{ contains(github.event.pull_request.labels.*.name, 'failed') }}' == 'true') {
              github.issues.removeLabel({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number,
                name: 'failed'
              })
            }
      - uses: actions/github-script@0.6.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number,
              labels: ['automated merge']
            })
